dist: xenial
language: node_js
cache: npm
notifications:
  email: false
node_js:
  - '14.5.0'
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run report-coverage
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  only:
  - master
services:
  - xvfb
install:
  - npm install